#!/bin/bash
# -----------------------------------------------------------------------------
# docker-minecraft /start script
#
# Authors: Isaac Bythewood, Paul Rosania
# Updated: Apr 28th, 2014
# -----------------------------------------------------------------------------


# Copy over the base database to our data directory if it doesn't exist
if [ ! -f /srv/minecraft/minecraft_server.jar ]
then
    cd /srv/minecraft
    cp /usr/local/etc/minecraft/ops.txt .
    cp /usr/local/etc/minecraft/white-list.txt .
    cp /usr/local/etc/minecraft/server.properties .
    curl https://s3.amazonaws.com/Minecraft.Download/versions/1.7.9/minecraft_server.1.7.9.jar -o minecraft_server.jar
fi


# Run supervisor which maintains the minecraft server
/usr/bin/supervisord

